### ISSUE TITLE
Unlicense is broken

### ISSUE THREAD

**Issue by SBoudrias** [jozefizso/generator-license#19]
Original report on https://github.com/yeoman/generator-generator/issues/143

Seems to be an error with the filename:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
AssertionError: Trying to copy from a source that does not exist: /home/username/node_modules/lib/node_modules/generator-generator/node_modules/generator-node/node_modules/generator-license/app/templates/Unlicense.txt
    at EditionInterface.exports._copySingle (/home/username/node_modules/lib/node_modules/generator-generator/node_modules/generator-node/node_modules/generator-license/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:44:3)
    at EditionInterface.exports.copy (/home/username/node_modules/lib/node_modules/generator-generator/node_modules/generator-node/node_modules/generator-license/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:22:17)
    at EditionInterface.module.exports [as copyTpl] (/home/username/node_modules/lib/node_modules/generator-generator/node_modules/generator-node/node_modules/generator-license/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:9:8)
    at module.exports.generators.Base.extend.writing.license (/home/username/node_modules/lib/node_modules/generator-generator/node_modules/generator-node/node_modules/generator-license/app/index.js:98:15)
    at /home/username/node_modules/lib/node_modules/generator-generator/node_modules/generator-node/node_modules/generator-license/node_modules/yeoman-generator/lib/base.js:421:16
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by jozefizso** [comment]
Fixed in v3.0.0 release.
